# Generated by Django 6.0.4 on 2026-06-11 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_member_account_name_member_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='loanrepayment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Paystack', 'Paystack')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.member'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='core.loan'),
        ),
    ]
